# Generated by Django 5.0.6 on 2025-08-26 19:52

import profiles.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("profiles", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="avatar",
            field=models.ImageField(
                blank=True, null=True, upload_to=profiles.models.user_avatar_path
            ),
        ),
    ]
