# Generated by Django 5.0.6 on 2026-07-05 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0003_follow_profile_following_follow_uniq_follow_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='email_notifications',
            field=models.BooleanField(default=True),
        ),
    ]
