name: enviralyze

dependencies:
  - python=3.12.5
  - pip=24.2
  - pip:
      - django==5.0.6
      - djangorestframework==3.15.1
      - djangorestframework_simplejwt==5.3.1
      - drf-yasg==1.21.7
      - pillow==10.3.0
      - django-cors-headers==4.3.1
      - django-filter==24.2
      - tzdata==2025.2
      - psycopg2-binary==2.9.9
      - django-environ==0.12.0
      - django-allauth==65.3.1
      - dj-rest-auth==7.0.1
      - requests==2.32.5
      - cryptography==45.0.7