# Generated by Django 5.0.6 on 2025-09-25 18:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("lists", "0001_initial"),
        ("products", "0007_delete_productcomment"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="list",
            options={"ordering": ["-created"]},
        ),
        migrations.AddField(
            model_name="list",
            name="type",
            field=models.CharField(
                choices=[
                    ("custom", "Custom"),
                    ("favorite", "Favorite"),
                    ("compare", "Comparison"),
                ],
                default="custom",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="list",
            name="creator",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="lists",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterUniqueTogether(
            name="list",
            unique_together={("creator", "name", "type")},
        ),
        migrations.CreateModel(
            name="ListItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("added_at", models.DateTimeField(auto_now_add=True)),
                ("order", models.PositiveIntegerField(default=0)),
                (
                    "list",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="lists.list",
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="products.product",
                    ),
                ),
            ],
            options={
                "ordering": ["order", "-added_at"],
                "unique_together": {("list", "product")},
            },
        ),
        migrations.AddField(
            model_name="list",
            name="products",
            field=models.ManyToManyField(
                related_name="lists", through="lists.ListItem", to="products.product"
            ),
        ),
    ]
