# Generated by Django 5.0.6 on 2025-09-29 22:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("lists", "0002_alter_list_options_list_type_alter_list_creator_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="list",
            name="data",
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
    ]
