# Generated by Django 5.0.6 on 2025-09-29 23:25

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("lists", "0003_alter_list_data"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name="list",
            old_name="creator",
            new_name="owner",
        ),
        migrations.AlterUniqueTogether(
            name="list",
            unique_together={("owner", "name", "type")},
        ),
    ]
