# Generated by Django 5.0.6 on 2025-10-01 10:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("lists", "0004_rename_creator_list_owner_alter_list_unique_together"),
    ]

    operations = [
        migrations.RenameField(
            model_name="list",
            old_name="is_shared",
            new_name="is_public",
        ),
    ]
