# Generated by Django 5.0.6 on 2025-10-01 12:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("lists", "0005_rename_is_shared_list_is_public"),
    ]

    operations = [
        migrations.RenameField(
            model_name="list",
            old_name="is_public",
            new_name="is_shared",
        ),
    ]
