# Generated by Django 5.0.6 on 2025-10-01 12:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("lists", "0006_rename_is_public_list_is_shared"),
    ]

    operations = [
        migrations.RenameField(
            model_name="list",
            old_name="is_shared",
            new_name="is_public",
        ),
    ]
