# Generated by Django 5.0.6 on 2025-09-12 18:36

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="barcode",
            field=models.CharField(
                max_length=14,
                unique=True,
                validators=[
                    django.core.validators.RegexValidator(
                        "^\\d{8,14}$", "Barcode must be 8–14 digits"
                    )
                ],
            ),
        ),
    ]
