# Generated by Django 5.0.6 on 2025-09-17 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0003_product_image_url_product_last_synced_at_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="last_checked_at",
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name="product",
            name="off_etag",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="product",
            name="last_synced_at",
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
    ]
