# Generated by Django 5.0.6 on 2025-09-23 15:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0006_userproductinteraction"),
    ]

    operations = [
        migrations.DeleteModel(
            name="ProductComment",
        ),
    ]
